server:
 port: 8090

spring:
 redis:
  database: 1
  host: 116.196.121.21
  port: 6379
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: 123456
  url: jdbc:mysql://localhost:3306/xusihan?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf-8&useSSL=false
  
